
import React from 'react';
import OutputCard from '@/components/spa/OutputCard';
import { 
  Wand2, Puzzle, TestTube, Gauge, ScrollText, FileText, ListChecks, 
  Database, ChartBar, GitMerge, FileCode, FileCheck, FileJson, Network, 
  CheckCircle, HelpCircle, Server, Cog, LineChart, FileSpreadsheet, Shield, 
  Settings, Briefcase 
} from 'lucide-react';

const OutputsSection: React.FC = () => {
  return (
    <div id="outputs" className="mt-8 mb-12 scroll-mt-20">
      <div className="text-center mb-8">
        <h2 className="text-2xl font-semibold">SPA Outputs</h2>
        <p className="text-gray-600">Comprehensive deliverables generated by the SPA framework</p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {/* Generator Outputs */}
        <div className="glass-card p-5">
          <h3 className="text-lg font-semibold mb-4 flex items-center">
            <div className="w-8 h-8 rounded-full bg-[#007AFF] flex items-center justify-center mr-3">
              <Wand2 size={16} className="text-white" />
            </div>
            Generator Outputs
          </h3>
          <div className="space-y-3">
            <OutputCard title="Test Scenarios" description="Comprehensive coverage scenarios" icon={<ScrollText size={16} />} color="#007AFF" />
            <OutputCard title="Test Cases" description="Detailed step-by-step instructions" icon={<FileText size={16} />} color="#007AFF" />
            <OutputCard title="Test Steps" description="Granular verification points" icon={<ListChecks size={16} />} color="#007AFF" />
            <OutputCard title="Test Data" description="Synthetic and reference data sets" icon={<Database size={16} />} color="#007AFF" />
            <OutputCard title="Coverage Analysis" description="Gaps and risk assessments" icon={<ChartBar size={16} />} color="#007AFF" />
            <OutputCard title="Requirements Traceability" description="Mapping to source requirements" icon={<GitMerge size={16} />} color="#007AFF" />
            <OutputCard title="Automated Scripts" description="Framework-specific test code" icon={<FileCode size={16} />} color="#007AFF" />
          </div>
        </div>
        
        {/* Composer Outputs */}
        <div className="glass-card p-5">
          <h3 className="text-lg font-semibold mb-4 flex items-center">
            <div className="w-8 h-8 rounded-full bg-[#5856D6] flex items-center justify-center mr-3">
              <Puzzle size={16} className="text-white" />
            </div>
            Composer Outputs
          </h3>
          <div className="space-y-3">
            <OutputCard title="Golden Thread Test Suite" description="End-to-end business process validation" icon={<FileCheck size={16} />} color="#5856D6" />
            <OutputCard title="CR-XYZ_Test Suite" description="Change request validation package" icon={<FileText size={16} />} color="#5856D6" />
            <OutputCard title="E2E Test Suite" description="Complete user journey validation" icon={<GitMerge size={16} />} color="#5856D6" />
            <OutputCard title="Test Magic Scripts" description="Optimized execution code" icon={<FileCode size={16} />} color="#5856D6" />
            <OutputCard title="Test Data_ABC_Scenario" description="Context-specific test data" icon={<FileJson size={16} />} color="#5856D6" />
            <OutputCard title="Integration Test Flows" description="System interaction validations" icon={<Network size={16} />} color="#5856D6" />
            <OutputCard title="Regression Test Pack" description="Impact-based regression suite" icon={<CheckCircle size={16} />} color="#5856D6" />
          </div>
        </div>
        
        {/* Executor Outputs */}
        <div className="glass-card p-5">
          <h3 className="text-lg font-semibold mb-4 flex items-center">
            <div className="w-8 h-8 rounded-full bg-[#FF9500] flex items-center justify-center mr-3">
              <TestTube size={16} className="text-white" />
            </div>
            Executor Outputs
          </h3>
          <div className="space-y-3">
            <OutputCard title="Test Execution Logs" description="Detailed run history" icon={<ScrollText size={16} />} color="#FF9500" />
            <OutputCard title="Defect Reports" description="Automated bug tracking" icon={<HelpCircle size={16} />} color="#FF9500" />
            <OutputCard title="Environmental Validation" description="System readiness checks" icon={<Server size={16} />} color="#FF9500" />
            <OutputCard title="CI/CD Integration Results" description="Pipeline gate metrics" icon={<Cog size={16} />} color="#FF9500" />
            <OutputCard title="Performance Benchmarks" description="Speed and throughput metrics" icon={<LineChart size={16} />} color="#FF9500" />
            <OutputCard title="Screenshot Comparisons" description="Visual regression outputs" icon={<FileSpreadsheet size={16} />} color="#FF9500" />
            <OutputCard title="Execution Dashboards" description="Real-time monitoring views" icon={<ChartBar size={16} />} color="#FF9500" />
          </div>
        </div>
        
        {/* Manager Outputs */}
        <div className="glass-card p-5">
          <h3 className="text-lg font-semibold mb-4 flex items-center">
            <div className="w-8 h-8 rounded-full bg-[#34C759] flex items-center justify-center mr-3">
              <Gauge size={16} className="text-white" />
            </div>
            Manager Outputs
          </h3>
          <div className="space-y-3">
            <OutputCard title="Project_ABC_Metric" description="Project-specific KPIs" icon={<LineChart size={16} />} color="#34C759" />
            <OutputCard title="Monthly Performance Report" description="Trend analysis and insights" icon={<FileSpreadsheet size={16} />} color="#34C759" />
            <OutputCard title="Project Status Report" description="Executive dashboards" icon={<ChartBar size={16} />} color="#34C759" />
            <OutputCard title="Metrics and Risk Ledger" description="Risk assessment and mitigation" icon={<Shield size={16} />} color="#34C759" />
            <OutputCard title="Certification Documents" description="Compliance validation" icon={<FileCheck size={16} />} color="#34C759" />
            <OutputCard title="Resource Utilization" description="Environment and tool usage" icon={<Settings size={16} />} color="#34C759" />
            <OutputCard title="Sign-off Records" description="Approval documentation" icon={<Briefcase size={16} />} color="#34C759" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default OutputsSection;
